bdd = {
	france = {
		langue = {"français"},
		capitale = "paris",
		monnaie = "euro",
		religion ={""},
		regime = "république constitutionnelle",
		population = "66,6 millions",
		superficie = "Over 9000",
		continent = "Europe",
		position = {"Europe de l'Ouest"},
		pays_frontalier = {"belgique", "espagne", "allemagne", "suisse", "italie", "luxembourg", "andorre", "monaco", "liechtenstein"},
	},
	hyrule = {
		langue = {"hylien"},
		capitale = "chateau d'hyrule",
		monnaie = "rubis",
		religion ={"polythéiste"},
		position = {"DTC"},
		pays_frontalier = {"royaume champignon", "zebes", "kanto"},
		population = "69 420",
		regime = "monarchie",
		continent = "nintendo land",
		superficie = "987654 km2",
	},
	twitch = {
		langue = {"Kappa", "TriHex", "ResidentSleeper", "PogChamp", "Kreygasm", "OpieOP"},
		capitale = "Cosmo",
		monnaie = "FrankerZ",
		religion ={"Helix Fossil"},
		position = {"4chan"},
		pays_frontalier = {"reddit", "facebook", "twitter", "youporn", "redtube"},
		population = "Over 9000",
		regime = "Anarchy",
		continent = "Internet",
		superficie = "1 8 1 0 ",
	},
	modele = {
		langue = {},
		monnaie = "",
		religion ={},
		position = {},
		pays_frontalier = {},
		population = "",
		regime = "",
		continent = "",
		superficie = "",
	},
}
