bdd = {
	france = {
		langue = {"français"},
		capitale = "paris",
		monnaie = "euro",
		religion = {},
		regime = "république constitutionnelle",
		population = "66,6 millions",
		superficie = "Over 9000",
		continent = "Europe",
		position = {"Europe de l'Ouest"},
		pays_frontalier = {"belgique", "espagne", "allemagne", "suisse", "italie", "luxembourg", "andorre", "monaco", "liechtenstein"},
	},
	allemagne = {
		langue = {"hylien"},
		capitale = "chateau d'hyrule",
		monnaie = "rubis",
		religion ={"polythéiste"},
		position = {"DTC"},
		pays_frontalier = {"royaume champignon", "zebes", "kanto"},
		population = "69 420",
		regime = "monarchie",
		continent = "nintendo land",
		superficie = "987654 km2",
	},
}
